eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  rabbitmq:
    host: localhost    
    port: 5672
    username: guest
    password: guest   
management:
  endpoints:
    web:
      exposure:
        include: '*'
