server:
   port: 8080
   
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/

hello: hello

---
spring:
  profile: local
    greeting: 
  datasource:
       data: classpath:data-h2-utf8-nobom.sql   
  jpa:
     show-sql: true
     hibernate:
        ddl-auto: create-drop
        use-new-id-generator-mappings: false
  h2:
    console:
      enabled: true

  cloud:
    config:
      uri: http://localhost:8888

 ---
 spring:
   profile: dev
     greeting: 개발서버입니다
 
 ---
 spring:
   profile: default
     greeting: 운영서버입니다
  
