server:
   port: 8080
   
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/
greeting : 안녕하세요
hello: hello

spring:
  datasource:
       data: classpath:data-h2-utf8-nobom.sql   
  jpa:
     show-sql: true
     hibernate:
        ddl-auto: create-drop
        use-new-id-generator-mappings: false
  h2:
    console:
      enabled: true
  
  application:  
    name: micro-service-a
    
  cloud:
    config:
      uri: http://localhost:8888
      name: micro-service-a
