spring: 
  datasource:
       data: classpath:data-h2-utf8-nobom.sql   
  jpa:
     show-sql: true
     hibernate:
        ddl-auto: create-drop
        use-new-id-generator-mappings: false
  h2:
    console:
      enabled: true
  cloud:
    config:
      uri: http://localhost:8999
server:
   port: 8080   
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/

my: 
  greeting: gggggggggg
  hello: new hello2yyhhbb
