spring: 
  datasource:
       data: classpath:data-h2-utf8-nobom.sql   
  jpa:
     show-sql: true
     hibernate:
        ddl-auto: create-drop
        use-new-id-generator-mappings: false
  h2:
    console:
      enabled: true


my: 
  greeting: fdddddddfffff
  hello: new hello2yyhhbb
  
a: this is A
b: this is B
c: this is C
d: this is D
e: this is E
